env:
    token: "ENCRYPTED[91aa86249a2b8217c4416fd0688d5f96bd0f1c00043f546a4c588cc41f1e1e9233082dbd36ac2f5624e3843ff1136e63]"
    chat_id: "-1001659048493"
    
task:
  name: "Kernel deploy.."
  timeout_in: 120m
  container:
      image: nexgang/ubuntu:latest
      cpu: 4
      memory: 16G
      stateful: true
      greedy: true

  Build_script:
      - git clone --depth=1 -b los https://github.com/projects-nexus/nexus_kernel_xiaomi_lavender lv && cd lv
      - git fetch https://github.com/RooGhz720/kernel_xiaomi_lavender a13-cam && git cherry-pick 0df5d638e4d35ccb217e452446066330bacf4b9e^..3e5e85449704d002dcc59ab07c51908e55796933
      - /noclone3 bash build.sh --old
